# ============================================================
# mkdocs.yaml (MkDocs configuration file)
# ============================================================

# REQ.PROJECT: MkDocs configuration file (mkdocs.yaml)
#      to automatically build an associated website
#      for professional project documentation and communication.
#      Requires:
#         1. this file in the root of your project repository
#         2. docs/ folder with markdown files (.md) for content
#         3. GitHub Actions workflow to build and deploy site (in .github/workflows/)
#
# WHY-FILE: This data file provides the site structure and settings

site_name: "DataFun Toolkit"
site_url: https://denisecase.github.io/datafun-toolkit/
repo_url: https://github.com/denisecase/datafun-toolkit
site_description: Project documentation.
site_author: Denise M. Case
docs_dir: docs
site_dir: site
copyright: Copyright &copy; 2026 Denise M. Case
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/denisecase/datafun-toolkit
  languages:
    - name: English
      code: en
      default: true
    - name: Français
      code: fr
    - name: Ελληνικά
      code: el

# WHY: Material theme is industry standard, well-documented
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top # Back-to-top button
    - search.suggest # Search suggestions while typing
    - search.highlight # Highlight search terms
    - content.code.copy # Copy button on code blocks
    - toc.follow # Highlight current section in TOC

  palette:
    - scheme: default # Light/dark mode toggle
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search # WHY: Built-in search functionality
  - mike # WHY: Multi-version documentation management
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src/python/src
          options:
            show_source: true
            show_root_heading: true # Include module names
            show_root_toc_entry: true # Include module in TOC
            docstring_style: google # Professional docstring format
            show_signature_annotations: true
            separate_signature: true # Makes function signatures easier to read
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: fr
          name: Français
          build: false
        - locale: el
          name: Ελληνικά
          build: false

nav:
  - Site: index.md
  - Home: en/index.md
  - API: en/api.md
  - Examples: en/examples.md
  - Troubleshooting: en/troubleshooting.md
